version: "3.9"
services:
  redis:
    image: "redis:latest"
    networks:
      - mynetworks
    restart: always
  flask01:
    image: "betcybabu/ipstack:version1"
    networks:
      - mynetworks
    restart: always
    ports:
      - 8081:8080
    environment:
      CACHING_SERVER: redis
      IPSTACK_KEY: "3a0564c365882306f530060f2e7ad14a"
  flask02:
    image: "betcybabu/ipstack:version1"
    networks:
      - mynetworks
    restart: always
    ports:
      - 8082:8080
    environment:
      CACHING_SERVER: redis
      IPSTACK_KEY: "3a0564c365882306f530060f2e7ad14a"
  flask03:
    image: "betcybabu/ipstack:version1"
    networks:
      - mynetworks
    restart: always
    ports:
      - 8083:8080
    environment:
      CACHING_SERVER: redis
      IPSTACK_KEY: "3a0564c365882306f530060f2e7ad14a"
networks:
  mynetworks:
